<?php
  define('PRIMARY_PROFILE', 151);
  define('SERVICELISTING_PROFILE1', 152);
  define('SERVICELISTING_PROFILE2', 153);
  define('CAMP_CG', 72);
  define('DISPLAY_NAME', 'custom_900');
  define('DISPLAY_EMAIL', 'custom_901');
  define('DISPLAY_PHONE', 'custom_902');
  define('WAIVER_FIELD', 'custom_903');
  define('IS_REGULATED_SERVICE', 'custom_894');
  define('REGULATED_SERVICE_CF', 'custom_895');
  define('PRIMARY_CONTACT_REL', 74);
  define('STATUS', 'custom_904');
  define('RECEIVED_MESSAGE', 90);
  define('APPROVED_MESSAGE', 91);
  define('OTHER_LANGUAGE', 'custom_905');
  define('LANGUAGES', 'custom_899');
