<?php
  define('PRIMARY_PROFILE', 148);
  define('SERVICELISTING_PROFILE1', 146);
  define('SERVICELISTING_PROFILE2', 147);
  define('CAMP_CG', 70);
  define('DISPLAY_NAME', 'custom_868');
  define('DISPLAY_EMAIL', 'custom_869');
  define('DISPLAY_PHONE', 'custom_870');
  define('WAIVER_FIELD', 'custom_871');
  define('REGULATED_SERVICE_CF', 'custom_863');
  define('PRIMARY_CONTACT_REL', 74);
  define('STATUS', 'custom_872');
  define('RECEIVED_MESSAGE', 90);
  define('APPROVED_MESSAGE', 91);
